mappings:
  MinFraudAPIConnector: Sunnysideup\EcommerceMaxmindMinfraud\Api\MinFraudAPIConnector
  OrderStep_FraudCheck: Sunnysideup\EcommerceMaxmindMinfraud\Model\Process\OrderStepFraudCheck
  OrderStep_RecordDeviceDetails: Sunnysideup\EcommerceMaxmindMinfraud\Model\Process\OrderStepRecordDeviceDetails
  OrderStatusLog_MinFraudStatusLog: Sunnysideup\EcommerceMaxmindMinfraud\Model\Process\OrderStatusLogMinFraudStatusLog
  OrderStatusLog_DeviceDetails: Sunnysideup\EcommerceMaxmindMinfraud\Model\Process\OrderStatusLogDeviceDetails
